#spring.datasource.driverClassName=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/test
#spring.datasource.username=root
#spring.datasource.password=263282

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
spring.mvc.static-path-pattern: /resources/static/**

restTemplate:
  factory:
    readTimeout: 5000 
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5

logging:
  path: c:/dev/log/spring
  file: log-file  
  
---
spring:
  profiles: log-file-windows
  
logging:
  path: c:/dev/log/spring

---
spring:
  profiles: log-file-linux
  
logging:
  path: /log/spring/
